added german as language
silverweed/lifish pull request #14
Opened 2022-08-27 09:29 UTC by bl00dy1837

2022-08-29 07:35 UTC, silverweed requested changes
Many thanks for the contribution!
I just spotted a minor mistake, if you could please fix it I'll be happy to merge :)

2022-08-29 07:35 UTC, silverweed commented on assets/l10n/strings.json
> +		"it": "Nuova Partitai",
There is a stray 'i' at the end of the italian version, please remove it

2022-08-29 07:49 UTC, silverweed approved these changes

2022-08-29 07:54 UTC, merged

2022-08-29 07:55 UTC, silverweed commented
Thanks again, I merged the changes :)
I'll try to rebuild the game and do a new release as soon as I can (I should really set up CI to do that automatically...)

2022-08-29 08:07 UTC, bl00dy1837 commented
You’re welcome.
Sorry for the "i" it was late, vim typo.  :)
Like the game. Thx for it

2022-08-29 08:33 UTC, silverweed commented
Btw I fixed the layout of the German win screen by changing a couple of newlines (as some lines were too long).
I also noticed that a couple of strings weren't localized so I fixed that too (I hope "du hast gewonnen" is a good translation for "you have won" - otherwise please tell me a better one :D)

2022-08-30 06:57 UTC, bl00dy1837 commented
"Du hast gewonnen" is perfect. :) thx